### ISSUE TITLE
Antisymmetrical Tensors

### ISSUE THREAD

**Issue by gevero** [HomerReid/buff-em#1]
Hi Homer

I see that you are writing one more awesome code. I have just one brief question: is it possible to use also antisymmetrical tensor, in order to study the Magneto-optical properties of a system?

Best

Giovanni

**Comment by HomerReid** [comment]
Definitely--the ability to study objects with arbitrary 3x3 permittivity tensors is the main reason for the existence of **buff-em.**

**Comment by gevero** [comment]
Awesome

I will try to put it to good use!!!
